clone:
  depth: full
pipelines:
  branches:
    master:
      - step:
          name: Clone to GitHub
          script:
            - git remote add upstream git@github.com:intellio/terraform-aws-databricks-starter.git
            - git push --force upstream $BITBUCKET_BRANCH